name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: ast
      run:
        go test -v ./ast
    - name: Parser
      run:
        go test -v ./parser
    - name: pratt_parser
      run:
        go test -v ./parser/pratt_parser
    - name: VM
      run:
        go test -v ./vm

  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: VM
      run: 
        go run vm/vm.go
    - name: Parser
      run:
        go run parser/parser.go
    - name: pratt_parser
      run:
        go run parser/pratt_parser/pratt_parser.go
